#!/bin/sh
# Origin: EmberBSD; AI-assisted CAN test release-set regression.
# SPDX-License-Identifier: BSD-2-Clause
#
# Compare real make install metadata with the real release-set selector.
# The checkflist fixture checks extra CAN files only (-m permits unrelated
# missing files). It is deliberately not a complete release DESTDIR check.

set -eu
[ "$#" -eq 2 ] || {
	printf 'usage: %s source-tree new-output-directory\n' "$0" >&2
	exit 2
}
src=$(CDPATH= cd -- "$1" && pwd)
mkdir "$2"
out=$(CDPATH= cd -- "$2" && pwd)
export LC_ALL=C MAKECONF=/dev/null USETOOLS=no
export EMBER_SETLIST_SOURCE="$src"
export EMBER_SETLIST_MAKE="${SETLIST_MAKE:-/usr/bin/make}"
export NETBSDSRCDIR="$src"
cat > "$out/make" <<'WRAPPER'
#!/bin/sh
exec "$EMBER_SETLIST_MAKE" -m "$EMBER_SETLIST_SOURCE/share/mk" "$@"
WRAPPER
chmod 700 "$out/make"
export MAKE="$out/make"
failed=0

query()
{
	dir=$1
	shift
	"$MAKE" -C "$src/$dir" "$@"
}

check()
{
	label=$1
	export MACHINE=$2 MACHINE_ARCH=$3 MKATF=$4 MKRUMP=$5 MKDEBUG=$6
	export MKCOMPAT=$7 MKCOMPATTESTS=yes ACTIVE_CC=$8
	export MKKMOD=no MKCOMPATMODULES=no MKX11=no
	if [ "$ACTIVE_CC" = clang ]; then
		export HAVE_GCC=0 HAVE_LLVM=yes
	else
		unset HAVE_GCC HAVE_LLVM
	fi
	expected="$out/$label.expected"
	actual="$out/$label.actual"
	: > "$expected"
	if [ "$MKATF" = yes ] && [ "$MKRUMP" = yes ]; then
		programs=$(query tests/net/can -V '${TESTS_C}')
		debugdir=$(query tests/net/can -V '${DEBUGDIR}')
		for program in $programs; do
			bindir=$(query tests/net/can -V "\${BINDIR.$program}")
			name=$(query tests/net/can -V "\${PROGNAME.$program}")
			printf '.%s/%s\n' "$bindir" "$name" >> "$expected"
			debug=$(query tests/net/can -V "\${_PROGDEBUG.$program}")
			if [ -n "$debug" ]; then
				printf '.%s%s/%s\n' "$debugdir" "$bindir" \
				    "$debug" >> "$expected"
			fi
		done
	fi
	sort -o "$expected" "$expected"
	sh "$src/distrib/sets/makeflist" tests debug \
	    > "$out/$label.flist" 2> "$out/$label.stderr"
	if [ -s "$out/$label.stderr" ]; then
		cat "$out/$label.stderr" >&2
		exit 1
	fi
	# Include any compat copies in actual, so unexpected copies also fail.
	awk '/\/net\/can\// && !/\/(Atffile|Kyuafile)$/ { print }' \
	    "$out/$label.flist" > "$actual"
	rm "$out/$label.flist"
	if ! diff -u "$expected" "$actual" > "$out/$label.diff"; then
		cat "$out/$label.diff"
		failed=1
	fi
	"$MAKE" -f "$src/distrib/sets/mkvars.mk" \
	    -V '${MKCOMPAT}' -V '${MKCOMPATTESTS}' -V '${COMPATARCHDIRS}' \
	    -V '${ACTIVE_CC}' \
	    > "$out/$label.compat"
	if [ "$MKCOMPAT" = yes ]; then
		[ "$(sed -n '1p' "$out/$label.compat")" = yes ]
		[ -n "$(sed -n '3p' "$out/$label.compat")" ]
	fi
	[ "$(sed -n '4p' "$out/$label.compat")" = "$ACTIVE_CC" ]
	printf '%s: %s expected CAN paths, %s selected\n' "$label" \
	    "$(wc -l < "$expected" | tr -d ' ')" \
	    "$(wc -l < "$actual" | tr -d ' ')"

	case "$label" in
	aarch64-debug|aarch64-no-debug)
		# Use paths generated by bsd.test.mk/bsd.prog.mk, not the set list.
		dest="$out/$label.destdir"
		mkdir "$dest"
		while IFS= read -r path; do
			mkdir -p "$dest/${path%/*}"
			: > "$dest/$path"
		done < "$expected"
		status=0
		DESTDIR="$dest" sh "$src/distrib/sets/checkflist" -m \
		    > "$out/$label.checkflist.log" 2>&1 || status=$?
		printf '%s\n' "$status" > "$out/$label.checkflist.exit"
		cp "$dest/SETS.destdir.extra" "$out/$label.checkflist.extra"
		if [ "$status" -ne 0 ]; then
			cat "$out/$label.checkflist.extra"
			failed=1
		fi
		printf '%s: scoped checkflist -m exit=%s\n' "$label" "$status"
		gzip "$out/$label.checkflist.log"
		rm -rf "$dest"
		;;
	esac
}

check aarch64-debug evbarm aarch64 yes yes yes no gcc
check aarch64-no-debug evbarm aarch64 yes yes no no gcc
check aarch64-no-atf evbarm aarch64 no yes yes no gcc
check aarch64-no-rump evbarm aarch64 yes no yes no gcc
check aarch64eb-debug evbarm aarch64eb yes yes yes no gcc
check arm-debug evbarm earmv7hf yes yes yes no gcc
check amd64-compat-debug amd64 x86_64 yes yes yes yes gcc
check amd64-compat-no-debug amd64 x86_64 yes yes no yes gcc
check amd64-no-compat amd64 x86_64 yes yes yes no gcc
check aarch64-clang-compat evbarm aarch64 yes yes yes yes clang
check aarch64-clang-compat-no-debug evbarm aarch64 yes yes no yes clang

# Confirm that the actual compat build traversal excludes CAN, rather than
# accidentally omitting files from a build that would have installed them.
for variant in amd64/i386 arm/eabi arm/eabihf; do
	case "$variant" in
	amd64/*)
		export MACHINE=amd64 MACHINE_ARCH=x86_64 ACTIVE_CC=gcc
		unset HAVE_GCC HAVE_LLVM
		;;
	arm/*)
		export MACHINE=evbarm MACHINE_ARCH=aarch64 ACTIVE_CC=clang HAVE_GCC=0
		export HAVE_LLVM=yes
		;;
	esac
	export MKATF=yes MKRUMP=yes MKDEBUG=yes MKCOMPAT=yes MKCOMPATTESTS=yes
	fragment="$src/compat/$variant/bsd.${variant##*/}.mk"
	subdirs=$(query tests/net BSD_MK_COMPAT_FILE="$fragment" \
	    -V '${TESTS_SUBDIRS}')
	printf '%s: %s\n' "$variant" "$subdirs" >> "$out/compat-traversal.log"
	case " $subdirs " in
	*' can '*) failed=1 ;;
	esac
done

if [ "$failed" -ne 0 ]; then
	printf '%s\n' 'FAIL: CAN test release-set contract'
	exit 1
fi
printf '%s\n' 'PASS: CAN set selection and scoped extra-file checks'
printf '%s\n' 'A complete release check still requires its full DESTDIR.'
