/*
 * Build configuration of the ESP-IDF headers and sources used by the NetBSD
 * port of the ESP32-S31 radio.  Station only, no Bluetooth coexistence, no
 * power saving, no persistent storage.
 */
#ifndef SDKCONFIG_H
#define SDKCONFIG_H

#define CONFIG_IDF_TARGET_ESP32S31 1
#define CONFIG_IDF_TARGET "esp32s31"
#define CONFIG_IDF_TARGET_ARCH_RISCV 1
#define CONFIG_SOC_WIFI_SUPPORTED 1
#define CONFIG_SOC_WIFI_HE_SUPPORT 1
#define CONFIG_XTAL_FREQ 40
#define CONFIG_FREERTOS_HZ 100
#define CONFIG_LOG_MAXIMUM_LEVEL 3
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_VERSION 1
#define CONFIG_LOG_TIMESTAMP_SOURCE_RTOS 1
#define CONFIG_BOOTLOADER_CPU_CLK_FREQ_MHZ 320

#define CONFIG_ESP_PHY_ENABLED 1
#define CONFIG_ESP_PHY_MAX_WIFI_TX_POWER 20
#define CONFIG_ESP_PHY_MAX_TX_POWER 20
#define CONFIG_ESP_PHY_PLL_TRACK_PERIOD_MS 1000
#define CONFIG_ESP_PHY_CALIBRATION_MODE 2

#define CONFIG_ESP_WIFI_ENABLED 1
#define CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM 8
#define CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM 16
#define CONFIG_ESP_WIFI_TX_BUFFER_TYPE 1
#define CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM 16
#define CONFIG_ESP_WIFI_DYNAMIC_RX_MGMT_BUF 0
#define CONFIG_ESP_WIFI_RX_MGMT_BUF_NUM_DEF 5
#define CONFIG_ESP_WIFI_AMPDU_TX_ENABLED 1
#define CONFIG_ESP_WIFI_AMPDU_RX_ENABLED 1
#define CONFIG_ESP_WIFI_TX_BA_WIN 6
#define CONFIG_ESP_WIFI_RX_BA_WIN 6
#define CONFIG_ESP_WIFI_MGMT_SBUF_NUM 32
#define CONFIG_ESP_WIFI_SOFTAP_BEACON_MAX_LEN 752
#define CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM 7
#define CONFIG_ESP_WIFI_TX_HETB_QUEUE_NUM 3
#define CONFIG_ESP_WIFI_RMAC_AUTO_RESET_INTERVAL 0
#define CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE 0
#define CONFIG_ESP_WIFI_GCMP_SUPPORT 1
#define CONFIG_ESP_WIFI_GMAC_SUPPORT 1

#endif
